severity: error

linters:

  BorderZero:
    enabled: true
    convention: zero

  BemDepth:
    enabled: true

  ChainedClasses:
    enabled: true

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: true

  Comment:
    enabled: true

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: true

  ElsePlacement:
    style: new_line

  EmptyLineBetweenBlocks:
    enabled: true

  FinalNewline:
    enabled: true

  HexLength:
    enabled: true
    style: short

  HexValidation:
    enabled: true

  IdSelector:
    enabled: true

  ImportantRule:
    enabled: true

  ImportPath:
    enabled: true

  Indentation:
    enabled: true

  LeadingZero:
    enabled: true

  LengthVariable:
    enabled: true

  MergeableSelector:
    enabled: true

  NameFormat:
    enabled: true

  NestingDepth:
    enabled: true
    ignore_parent_selectors: true

  PlaceholderInExtend:
    enabled: true

  PrivateNamingConvention:
    enabled: true
    prefix: _

  PropertySortOrder:
    enabled: true
    order: recess

  PropertySpelling:
    enabled: true

  PropertyUnits:
    global: ['em', 'rem', '%'] # Allow relative units globally
    properties:
      line-height: ['em']
      margin: ['em', 'rem']  # No % allowed

  PseudoElement:
    enabled: true

  QualifyingElement:
    enabled: true

  SelectorDepth:
    enabled: true
    max_depth: 3

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
    class_convention: ^(?!js-).*
    class_convention_explanation: should not be written in the form js-*

  Shorthand:
    enabled: true

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  SpaceAfterComma:
    enabled: true

  SpaceAfterComment:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true

  SpaceAfterPropertyName:
    enabled: true

  SpaceAfterVariableColon:
    enabled: true

  SpaceAfterVariableName:
    enabled: true

  SpaceAroundOperator:
    enabled: true

  SpaceBeforeBrace:
    enabled: true

  SpaceBetweenParens:
    enabled: true

  StringQuotes:
    enabled: true
    style: single_quotes

  TrailingSemicolon:
    enabled: true

  TrailingWhitespace:
    enabled: true

  TransitionAll:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  VariableForProperty:
    enabled: true

  VendorPrefix:
    enabled: true

  ZeroUnit:
    enabled: true
